version: '3.8'

services:
  postgres:
    image: postgres:15.2-alpine
    container_name: postgres_db
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - TZ=America/Sao_Paulo
      - PGTZ=America/Sao_Paulo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend
  redis:
    image: 'redis:8.0-rc1-alpine'
    container_name: redis
    restart: always
    env_file: .env
    ports:
      - '6379:6379'
    command: redis-server --requirepass ${REDIS_PASSWORD} --protected-mode no
    networks:
      - backend
  pgadmin:
    image: dpage/pgadmin4:7.8
    container_name: pgadmin
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=oi@oi.com.br
      - PGADMIN_DEFAULT_PASSWORD=password
      - TZ=America/Sao_Paulo
    ports:
      - '5050:80'
    depends_on:
      - postgres
    networks:
      - backend
volumes:
  postgres_data:

networks:
  backend:
    driver: bridge
